name: .NET build

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  PACKAGE_SOURCE: github

defaults:
  run:
    working-directory: d1-client-dotnet

jobs:
  github-push:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        path: d1-client-dotnet

    - name: Check out repository
      uses: actions/checkout@v2
      with:
        repository: cybercryptio/d1-service-generic
        path: d1-service-generic
        ref: v0.1.47-ci.71
        token: ${{ secrets.CYBOT_TOKEN }}

    - name: Check out repository
      uses: actions/checkout@v2
      with:
        repository: cybercryptio/d1-service-storage
        path: d1-service-storage
        ref: v0.1.25-ci.118
        token: ${{ secrets.CYBOT_TOKEN }}

    - name: Setup and cache dependencies
      uses: cybercryptio/build-setup-action@master

    - name: Install XmlDocMarkdown
      run: dotnet tool install xmldocmd -g

    - name: Build
      run: make build

    - name: Login into package feed
      run: |
        dotnet nuget add source --username cybot-cc --password ${{ secrets.CYBOT_TOKEN }} --store-password-in-clear-text --name ${{ env.PACKAGE_SOURCE }} "https://nuget.pkg.github.com/cybercryptio/index.json"

    - name: Publish
      run: make nuget-publish
      env:
        API_KEY: ${{ secrets.CYBOT_TOKEN }}
        VERSION: ${{ github.ref_name }}

  nuget-push:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        path: d1-client-dotnet

    - name: Check out repository
      uses: actions/checkout@v2
      with:
        repository: cybercryptio/d1-service-generic
        path: d1-service-generic
        ref: v0.1.25
        token: ${{ secrets.CYBOT_TOKEN }}

    - name: Check out repository
      uses: actions/checkout@v2
      with:
        repository: cybercryptio/d1-service-storage
        path: d1-service-storage
        ref: v0.1.12
        token: ${{ secrets.CYBOT_TOKEN }}

    - name: Setup and cache dependencies
      uses: cybercryptio/build-setup-action@master

    - name: Install XmlDocMarkdown
      run: dotnet tool install xmldocmd -g

    - name: Build
      run: make build

    - name: Publish
      run: make nuget-publish
      env:
        PACKAGE_SOURCE: https://api.nuget.org/v3/index.json
        API_KEY: ${{ secrets.NUGET_API_KEY }}
        VERSION: ${{ github.ref_name }}
